# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_import_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.operations_column = QtWidgets.QVBoxLayout()
        self.operations_column.setObjectName("operations_column")
        self.to_import_image_show = QtWidgets.QLabel(Dialog)
        self.to_import_image_show.setMinimumSize(QtCore.QSize(200, 200))
        self.to_import_image_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.to_import_image_show.setTextFormat(QtCore.Qt.AutoText)
        self.to_import_image_show.setAlignment(QtCore.Qt.AlignCenter)
        self.to_import_image_show.setObjectName("to_import_image_show")
        self.operations_column.addWidget(self.to_import_image_show)
        self.name_edit = QtWidgets.QLineEdit(Dialog)
        self.name_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.name_edit.setInputMask("")
        self.name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.name_edit.setObjectName("name_edit")
        self.operations_column.addWidget(self.name_edit)
        self.import_image = QtWidgets.QPushButton(Dialog)
        self.import_image.setObjectName("import_image")
        self.operations_column.addWidget(self.import_image)
        self.generate_old = QtWidgets.QPushButton(Dialog)
        self.generate_old.setObjectName("generate_old")
        self.operations_column.addWidget(self.generate_old)
        self.sync_json = QtWidgets.QPushButton(Dialog)
        self.sync_json.setObjectName("sync_json")
        self.operations_column.addWidget(self.sync_json)
        self.horizontalLayout.addLayout(self.operations_column)
        self.display_column = QtWidgets.QVBoxLayout()
        self.display_column.setObjectName("display_column")
        self.to_reco_image_show = QtWidgets.QHBoxLayout()
        self.to_reco_image_show.setObjectName("to_reco_image_show")
        self.generated_images_show = QtWidgets.QLabel(Dialog)
        self.generated_images_show.setMinimumSize(QtCore.QSize(500, 300))
        self.generated_images_show.setAlignment(QtCore.Qt.AlignCenter)
        self.generated_images_show.setObjectName("generated_images_show")
        self.to_reco_image_show.addWidget(self.generated_images_show)
        self.display_column.addLayout(self.to_reco_image_show)
        self.btn_input_to_reco_image = QtWidgets.QPushButton(Dialog)
        self.btn_input_to_reco_image.setObjectName("btn_input_to_reco_image")
        self.display_column.addWidget(self.btn_input_to_reco_image)
        self.log_text = QtWidgets.QLabel(Dialog)
        self.log_text.setMaximumSize(QtCore.QSize(16777215, 25))
        self.log_text.setAlignment(QtCore.Qt.AlignCenter)
        self.log_text.setObjectName("log_text")
        self.display_column.addWidget(self.log_text)
        self.horizontalLayout.addLayout(self.display_column)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.to_import_image_show.setText(_translate("Dialog", "<html><head/><body><p>将导入的图片</p><p>识别结果图片</p><p>复用窗口</p></body></html>"))
        self.name_edit.setText(_translate("Dialog", "输入导入相片中人的名字"))
        self.import_image.setText(_translate("Dialog", "导入图片"))
        self.generate_old.setText(_translate("Dialog", "生成跨年龄图片模型"))
        self.sync_json.setText(_translate("Dialog", "同步资源文件"))
        self.generated_images_show.setText(_translate("Dialog", "<html><head/><body><p>跨年龄图片集</p><p>导入待识别人像预览</p><p>复用窗口</p></body></html>"))
        self.btn_input_to_reco_image.setText(_translate("Dialog", "导入待跨年龄识别的人像照片"))
        self.log_text.setText(_translate("Dialog", "日志输出"))
