# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_single_pic.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 670)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_show = QtWidgets.QLabel(Dialog)
        self.result_show.setMinimumSize(QtCore.QSize(0, 300))
        self.result_show.setAlignment(QtCore.Qt.AlignCenter)
        self.result_show.setObjectName("result_show")
        self.verticalLayout.addWidget(self.result_show)
        self.btn_import_image = QtWidgets.QPushButton(Dialog)
        self.btn_import_image.setObjectName("btn_import_image")
        self.verticalLayout.addWidget(self.btn_import_image)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pic_show = QtWidgets.QLabel(Dialog)
        self.pic_show.setMinimumSize(QtCore.QSize(600, 650))
        self.pic_show.setMaximumSize(QtCore.QSize(600, 650))
        self.pic_show.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_show.setObjectName("pic_show")
        self.verticalLayout_2.addWidget(self.pic_show)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.result_show.setText(_translate("Dialog", "结果输出"))
        self.btn_import_image.setText(_translate("Dialog", "输入单张图片以颜值打分"))
        self.pic_show.setText(_translate("Dialog", "选择的图像"))
